---
- name: Launch instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - fail:
      msg: "Deployment type not supported for OpenStack provider yet"
    when: deployment_type == 'online'

  # TODO: Write an Ansible module for dealing with HEAT stacks
  #       Dealing with the outputs is currently terrible

  - name: Check OpenStack stack
    command: 'heat stack-show openshift-ansible-{{ cluster_id }}-stack'
    register: stack_show_result
    changed_when: false
    failed_when: stack_show_result.rc != 0 and 'Stack not found' not in stack_show_result.stderr

  - name: Update OpenStack Stack
    command: 'heat stack-update -f {{ openstack_infra_heat_stack }}
             -P cluster_id={{ cluster_id }}
             -P dns_nameservers={{ openstack_network_dns | join(",") }}
             -P cidr={{ openstack_network_cidr }}
             -P ssh_incoming={{ openstack_ssh_access_from }}
             -P num_masters={{ num_masters }}
             -P num_nodes={{ num_nodes }}
             -P master_image={{ deployment_vars[deployment_type].image }}
             -P node_image={{ deployment_vars[deployment_type].image }}
             -P master_flavor={{ openstack_flavor["master"] }}
             -P node_flavor={{ openstack_flavor["node"] }}
             -P ssh_public_key="{{ openstack_ssh_public_key }}"
             openshift-ansible-{{ cluster_id }}-stack'
    when: stack_show_result.rc == 0

  - include: setup.yml

- include: update.yml

- include: list.yml
