---
openstack_infra_heat_stack:     "{{ opt_infra_heat_stack  | default('files/heat_stack.yml') }}"
openstack_network_prefix:       "{{ opt_network_prefix    | default('openshift-ansible-'+cluster_id) }}"
openstack_network_cidr:         "{{ opt_net_cidr          | default('192.168.' + ( ( cluster_id | oo_hash % 255 ) | string() ) + '.0/24') }}"
openstack_network_external_net: "{{ opt_external_net      | default('external') }}"
openstack_floating_ip_pools:    "{{ opt_floating_ip_pools | default('external')        | oo_split() }}"
openstack_network_dns:          "{{ opt_dns               | default('8.8.8.8,8.8.4.4') | oo_split() }}"
openstack_ssh_keypair:          "{{ opt_keypair           | default(lookup('env', 'LOGNAME')+'_key') }}"
openstack_ssh_public_key:       "{{ lookup('file', opt_public_key | default('~/.ssh/id_rsa.pub')) }}"
openstack_ssh_access_from:      "{{ opt_ssh_from          | default('0.0.0.0/0') }}"
openstack_flavor:
  master:
    ram:     "{{ opt_master_flavor_ram     | default(2048) }}"
    id:      "{{ opt_master_flavor_id      | default() }}"
    include: "{{ opt_master_flavor_include | default() }}"
  node:
    ram:     "{{ opt_node_flavor_ram     | default(4096) }}"
    id:      "{{ opt_node_flavor_id      | default() }}"
    include: "{{ opt_node_flavor_include | default() }}"

deployment_vars:
  origin:
    image:
      name: "{{ opt_image_name | default('centos-70-raw') }}"
      id:
    ssh_user: openshift
    sudo: yes
  online:
    image:
      name:
      id:
    ssh_user: root
    sudo: no
  enterprise:
    image:
      name: "{{ opt_image_name | default('centos-70-raw') }}"
      id:
    ssh_user: openshift
    sudo: yes
