---
# tasks file for openshift_master

  # fixme: Once openshift stops resolving hostnames for minion queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  hostname: name={{ oo_bind_ip }}

- name: Install docker
  yum: pkg=docker state=installed

- include: openshift_from_yum.yml
  when: oo_openshift_binary is not defined

- include: openshift_from_local.yml
  when: oo_openshift_binary is defined

- name: Open firewalld port for etcd embedded in OpenShift
  firewalld: port=4001/tcp permanent=false state=enabled

- name: Save firewalld port for etcd embedded in
  firewalld: port=4001/tcp permanent=true state=enabled

- name: Open firewalld port for OpenShift
  firewalld: port=8080/tcp permanent=false state=enabled

- name: Save firewalld port for OpenShift
  firewalld: port=8080/tcp permanent=true state=enabled

- name: Enable OpenShift
  service: name=openshift enabled=yes state=started
