---
# tasks file for openshift_master

  # fixme: Once openshift stops resolving hostnames for minion queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  hostname: name={{ oo_bind_ip }}

- include: openshift_from_yum.yml
  when: oo_openshift_binary is not defined

- include: openshift_from_local.yml
  when: oo_openshift_binary is defined

- name: Configure OpenShift Master settings
  lineinfile: >
    dest=/etc/sysconfig/openshift
    create=yes
    regexp={{ item.regex }}
    line="{{ item.line }}"
  with_items:
    - { regex: '^ROLE=', line: 'ROLE=\"master\"' }
    - { regex: '^OPTIONS=', line: 'OPTIONS=\"--nodes={{ oo_minion_ips | join(",") }}  --loglevel=1\"' }
  notify:
    - restart openshift-master

- name: Open firewalld port for etcd embedded in OpenShift
  firewalld: port={{ item[0] }} permanent={{ item[1] }} state=enabled
  with_nested:
    - [ 4001/tcp, 8080/tcp, 8443/tcp, 8444/tcp ]
    - [ true, false ]

- name: Enable OpenShift
  service: name=openshift enabled=yes state=started
