- name: "Gather facts for masters in {{ oo_env }}"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-master"
  connection: ssh
  user: root


# This should be done separetly
- name: "Set Origin specific facts on localhost (for later use)"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  gather_facts: no
  tasks:
  - name: Setting oo_master_ips fact on localhost
    set_fact:
      oo_master_ips: "{{ hostvars
          | oo_select_keys(groups['tag_env-host-type_' + oo_env + '-openshift-master'])
          | oo_collect(attribute='ansible_default_ipv4.address') }}"
      when: groups['tag_env-host-type_' + oo_env + '-openshift-master'] is defined


- name: "Configure instances"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  connection: ssh
  user: root
  vars_files:
  - vars.yml

  tags: config
  tasks:
  - name: re-read facts after adding custom fact
    setup: filter=ansible_local

  roles:
  - ../../../roles/base_os
  - ../../../roles/repos
  - {
     role: ../../../roles/overlay_network,
     oo_public_ip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(['']) }}"
    }
  - ../../../roles/docker
  - {
     role: ../../../roles/openshift_minion,
     oo_master_ips: "{{ hostvars['localhost'].oo_master_ips | default(['']) }}",
     oo_bind_ip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(['']) }}"
    }
