---
- name: "Force fact gathering"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  connection: ssh
  user: root
  tasks:
    - name: Gather fact
      setup: filter=ansible_local

- name: "Configure instances"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - { role: ../../../roles/minion_indices,
        oo_nb_minions: "{{ groups['tag_env-host-type_' + oo_env + '-openshift-minion'] | count }}"
        }

# Apply the configs, seprate so that just the configs can be run by themselves
- include: config.yml



