---
- name: "Force fact gathering"
  hosts: minions
  connection: ssh
  user: root
  tasks:
    - name: Gather fact
      setup: filter=ansible_local

- name: "Configure instances"
  hosts: minions
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - { role: ../../../roles/minion_indices,
        oo_nb_minions: "{{ groups['minions'] | count }}"
        }

# Apply the configs, seprate so that just the configs can be run by themselves
- include: config.yml



