- name: "Gather facts for minions in {{ oo_env }}"
  hosts: minions
  connection: ssh
  user: root

# This should be done separetly
- name: "Set Origin specific facts on localhost (for later use)"
  hosts: masters
  gather_facts: no
  tasks:
    - name: Setting oo_minion_ips fact on localhost
      set_fact:
        oo_minion_ips: "{{ hostvars
            | oo_select_keys(groups['minions'])
            | oo_collect(attribute='ansible_default_ipv4.address') }}"
      when: groups['minions'] is defined


- name: "Configure instances"
#  hosts: oo_hosts_to_config
  hosts: masters
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  tags: config

  tasks:
  - name: re-read facts after adding custom fact
    setup: filter=ansible_local


  roles:
    - ../../../roles/base_os
    - ../../../roles/repos
    - {
        role: ../../../roles/local_openshift_master,
        oo_minion_ips: "{{  hostvars['localhost'].oo_minion_ips | default(['']) }}",
        oo_bind_ip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(['']) }}"
      }
    - ../../../roles/pods

- name: Copy certificate files from master to minions
  hosts: minions
  connection: ssh
  user: root
  tasks:
    - name: Copy certificate files from master to minions
      synchronize: mode=push src=/var/run/openshift/openshift.local.certificates dest=/var/run/openshift set_remote_user=true
      #delegate_to: localhost


