- name: "Gather facts for minions in {{ oo_env }}"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  connection: ssh
  user: root

# This should be done separetly
- name: "Set Origin specific facts on localhost (for later use)"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-master"
  gather_facts: no
  tasks:
    - name: Setting oo_minion_ips fact on localhost
      set_fact:
        oo_minion_ips: "{{ hostvars
            | oo_select_keys(groups['tag_env-host-type_' + oo_env + '-openshift-minion'])
            | oo_collect(attribute='ansible_default_ipv4.address') }}"
      when: groups['tag_env-host-type_' + oo_env + '-openshift-minion'] is defined


- name: "Configure instances"
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-master"
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  tags: config

  tasks:
    - name: re-read facts after adding custom fact
      setup: filter=ansible_local

    - name: Check rsync is installed
      yum: name=rsync state=present


  roles:
    - ../../../roles/base_os
    - ../../../roles/repos
    - {
        role: ../../../roles/openshift_master,
        oo_minion_ips: "{{  hostvars['localhost'].oo_minion_ips | default(['']) }}",
        oo_bind_ip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(['']) }}"
      }
    - {
        role: ../../../roles/pods,
        oo_master_ip: "{{ groups['tag_env-host-type_' + oo_env + '-openshift-master'][0] }}"
      }

- name: Copy certificate files from master to minions
  hosts: "tag_env-host-type_{{ oo_env }}-openshift-minion"
  connection: ssh
  user: root
  tasks:
    - name: Create openshift certificate directory
      file: path=/var/run/openshift state=directory

    - name: Check rsync is installed
      yum: name=rsync state=present

    - name: Copy certificate files from master to minions
      synchronize: mode=push src=/var/run/openshift/openshift.local.certificates dest=/var/run/openshift set_remote_user=true
      delegate_to: "{{ groups['tag_env-host-type_' + oo_env + '-openshift-master'][0] }}" 


