---
# tasks file for docker
- name: Install docker
  yum: pkg=docker

- name: start and enable docker service
  service: name=docker enabled=yes state=started

- copy: src=enter-container.sh dest=/usr/local/bin/enter-container.sh mode=0755

# From the origin rpm there exists instructions on how to
# setup origin properly.  The following steps come from there
- name: Ensure that root is in the Docker group
  user: name=root groups=docker append=yes

