---
# tasks file for openshift_minion
- name: Install OpenShift
  yum: pkg=origin state=installed

  # fixme: Once openshift stops resolving hostnames for minion queries remove this...
- name: Set hostname to IP Addr (WORKAROUND)
  hostname: name={{ oo_bind_ip }}

- name: Configure OpenShift Minion settings
  lineinfile: >
    dest=/etc/sysconfig/openshift
    regexp={{ item.regex }}
    line="{{ item.line }}"
  with_items:
    - { regex: '^ROLE=', line: 'ROLE=\"node\"' }
    - { regex: '^OPTIONS=', line: 'OPTIONS=\"--master=http://{{ oo_master_ips[0] }}:8080  --loglevel=5\"' }
  notify:
    - restart openshift-minion

- name: Open firewalld port for OpenShift
  firewalld: port=10250/tcp permanent=false state=enabled

- name: Save firewalld port for OpenShift
  firewalld: port=10250/tcp permanent=true state=enabled

- name: Enable OpenShift
  service: name=openshift enabled=yes state=started

