- name: Copy OpenShift binary
  copy:
    src: '{{ oo_openshift_binary }}'
    dest: /usr/local/bin/openshift
    mode: 0755
  notify: restart openshift-minion

- name: Create openshift WorkingDirectory
  file: path=/var/run/openshift owner=root state=directory

- name: Configure OpenShift systemd unit
  copy: src=openshift.service dest=/etc/systemd/system/openshift.service
